let SLIDER = [
    {
        id: 1,
        title: 'Mega Summer Sale',
        header: 'BIG DISCOUNT UP TO 50%',
        desc: 'New arrival, high quality product only at SHIBA SHOP',
        img: './images/slider/slide-img-1.jpg',
    },
    {
        id: 2,
        title: 'Back To School',
        header: 'LAPTOP, PHONE SALE 70%',
        desc: 'LIMITED TIME ONLY ! LIMITED TIME ONLY ! LIMITED TIME ONLY !',
        img: './images/slider/slide-img-2.jpg',
    },
    {
        id: 3,
        title: 'Orders From $0',
        header: 'FREE SHIP ON THE WORLD',
        desc: 'When you orders from $0, you will get free shipping',
        img: './images/slider/slide-img-3.jpg',
    },
    {
        id: 4,
        title: 'Service 24/7',
        header: 'WE ARE ALWAYS HERE.',
        desc: 'The support team of SHIBA SHOP is always there',
        img: './images/slider/slide-img-4.jpg',
    },
];

let CATEGORIES = [
    {
        id: 1,
        name: 'LAPTOP',
        img: `./images/categories/category-img-1.jpg`,
    },
    {
        id: 2,
        name: 'WATCH',
        img: `./images/categories/category-img-2.jpg`,
    },
    {
        id: 3,
        name: 'KEYBOARD',
        img: `./images/categories/category-img-3.jpg`,
    },
    {
        id: 4,
        name: 'HEADPHONE',
        img: `./images/categories/category-img-4.jpg`,
    },
    {
        id: 5,
        name: 'CAMERA',
        img: `./images/categories/category-img-5.jpg`,
    },
    {
        id: 6,
        name: 'PHONE',
        img: `./images/categories/category-img-6.jpg`,
    },
];

let USERS = [
    {
        id: 1,
        fullname: 'Nguyen Thi ADMIN',
        address: 'Thanh pho HCM',
        phone: '0123456789',
        username: 'admin',
        password: '123',
        isAdmin: true,
        cart: [],
        wishList: [],
    },
    {
        id: 2,
        fullname: 'Nguyen Thi USER',
        address: 'Thanh pho HCM',
        phone: '0123456789',
        username: 'user',
        password: '123',
        isAdmin: false,
        cart: [],
        wishList: [],
        img: './images/user-1.jpg',
    },
];

let PRODUCTS = [
    {
        id: 1,
        name: 'MASTER HEADPHONE',
        sale: 189,
        price: 179,
        category: 'HEADPHONE',
        rate: 4,
        wish: 0,
        imgList: [
            './images/products/product-1-img-1.jpg',
            './images/products/product-1-img-2.jpg',
            './images/products/product-1-img-3.jpg',
            './images/products/product-1-img-4.jpg',
        ],
    },
    {
        id: 2,
        name: 'SUPER SINGLE CAMERA',
        sale: 154,
        price: 123,
        category: 'CAMERA',
        rate: 3,
        wish: 0,
        imgList: [
            './images/products/product-2-img-1.jpg',
            './images/products/product-2-img-2.jpg',
            './images/products/product-2-img-3.jpg',
        ],
    },
    {
        id: 3,
        name: 'GOOGLE HOME',
        sale: 213,
        price: 199,
        category: 'SMART',
        rate: 3,
        wish: 0,
        imgList: [
            './images/products/product-3-img-1.jpg',
            './images/products/product-3-img-2.jpg',
            './images/products/product-3-img-3.jpg',
            './images/products/product-3-img-4.jpg',
        ],
    },
    {
        id: 4,
        name: 'IPHONE 11',
        sale: 612,
        price: 534,
        category: 'PHONE',
        rate: 4,
        wish: 0,
        imgList: [
            './images/products/product-4-img-1.jpg',
            './images/products/product-4-img-2.jpg',
            './images/products/product-4-img-3.jpg',
        ],
        colorList: ['--red:1', '--black:2', '--yellow:3'],
    },
    {
        id: 5,
        name: 'POLAROID CAMERA',
        sale: 89,
        price: 84,
        category: 'CAMERA',
        rate: 3,
        wish: 0,
        imgList: [
            './images/products/product-5-img-1.jpg',
            './images/products/product-5-img-3.jpg',
            './images/products/product-5-img-2.jpg',
            './images/products/product-5-img-4.jpg',
        ],
        colorList: ['--black:1', '--blue:3'],
    },
    {
        id: 6,
        name: 'BLUETOOTH PINK',
        sale: 109,
        price: 95,
        category: 'HEADPHONE',
        rate: 5,
        wish: 0,
        imgList: [
            './images/products/product-6-img-1.jpg',
            './images/products/product-6-img-2.jpg',
            './images/products/product-6-img-3.jpg',
        ],
    },
    {
        id: 7,
        name: 'KEYBORD AKO',
        sale: 320,
        price: 232,
        category: 'KEYBOARD',
        rate: 3,
        wish: 0,
        imgList: [
            './images/products/product-7-img-1.jpg',
            './images/products/product-7-img-2.jpg',
            './images/products/product-7-img-3.jpg',
            './images/products/product-7-img-4.jpg',
        ],
    },
    {
        id: 8,
        name: 'ACER NITRO 5',
        sale: 6120,
        price: 5431,
        category: 'LAPTOP',
        rate: 3,
        wish: 0,
        imgList: [
            './images/products/product-8-img-1.jpg',
            './images/products/product-8-img-2.jpg',
            './images/products/product-8-img-3.jpg',
            './images/products/product-8-img-4.jpg',
        ],
    },
    {
        id: 9,
        name: 'Sony Alpha ILCE-7CL',
        sale: 1941,
        price: 1490,
        category: 'CAMERA',
        rate: 5,
        wish: 0,
        imgList: [
            './images/products/product-9-img-1.jpg',
            './images/products/product-9-img-2.jpg',
            './images/products/product-9-img-3.jpg',
        ],
    },
    {
        id: 10,
        name: 'Galaxy Z Flip 3',
        sale: 6120,
        price: 5431,
        category: 'PHONE',
        rate: 4,
        wish: 0,
        imgList: [
            './images/products/product-10-img-1.jpg',
            './images/products/product-10-img-2.jpg',
            './images/products/product-10-img-3.jpg',
            './images/products/product-10-img-4.jpg',
        ],
        colorList: ['--purple:1', '--black:2', '--yellow:3', '--gray:4'],
    },
    {
        id: 11,
        name: 'OPPO Reno6 Pro',
        sale: 6120,
        price: 5431,
        category: 'PHONE',
        rate: 3,
        wish: 0,
        imgList: [
            './images/products/product-11-img-1.jpg',
            './images/products/product-11-img-2.jpg',
        ],
        colorList: ['--gray:1', '--lightBlue:2'],
    },
    {
        id: 12,
        name: 'IPHONE 13',
        sale: 6120,
        price: 5431,
        category: 'PHONE',
        rate: 5,
        wish: 0,
        imgList: [
            './images/products/product-12-img-1.jpg',
            './images/products/product-12-img-2.jpg',
            './images/products/product-12-img-3.jpg',
            './images/products/product-12-img-4.jpg',
        ],
        colorList: ['--red:1', '--pink:2', '--black:3', '--white:4'],
    },
    {
        id: 13,
        name: 'Galaxy Z Fold 3',
        sale: 79,
        price: 68,
        category: 'PHONE',
        rate: 5,
        wish: 0,
        imgList: [
            './images/products/product-13-img-1.jpg',
            './images/products/product-13-img-2.jpg',
        ],
        colorList: ['--black:1', '--pink:2'],
    },
    {
        id: 14,
        name: 'Fujifilm Instax Mini 11',
        sale: 79,
        price: 68,
        category: 'CAMERA',
        rate: 5,
        wish: 0,
        imgList: [
            './images/products/product-14-img-1.jpg',
            './images/products/product-14-img-2.jpg',
            './images/products/product-14-img-3.jpg',
        ],
        colorList: ['--blue:1', '--white:2', '--purple:3'],
    },
    {
        id: 15,
        name: 'GOOGLE HOME',
        sale: 213,
        price: 199,
        category: 'SMART',
        rate: 5,
        wish: 0,
        imgList: [
            './images/products/product.jpg',
            './images/products/product.jpg',
            './images/products/product.jpg',
            './images/products/product.jpg',
        ],
    },
    {
        id: 16,
        name: 'MSI Gaming GF65',
        sale: 1941,
        price: 1490,
        category: 'LAPTOP',
        rate: 3,
        wish: 0,
        imgList: [
            './images/products/product-16-img-1.jpg',
            './images/products/product-16-img-2.jpg',
            './images/products/product-16-img-3.jpg',
        ],
    },
    {
        id: 17,
        name: 'Lenovo Ideapad 5 Pro',
        sale: 1941,
        price: 1490,
        category: 'LAPTOP',
        rate: 5,
        wish: 0,
        imgList: [
            './images/products/product-17-img-1.jpg',
            './images/products/product-17-img-2.jpg',
        ],
    },
    {
        id: 18,
        name: 'Asus ROG Strix Scope TKL Electro Punk',
        sale: 1941,
        price: 1490,
        category: 'KEYBOARD',
        rate: 5,
        wish: 0,
        imgList: [
            './images/products/product-18-img-1.jpg',
            './images/products/product-18-img-2.jpg',
            './images/products/product-18-img-3.jpg',
        ],
    },
    {
        id: 19,
        name: 'Cooler Master CK530 V2',
        sale: 1941,
        price: 1490,
        category: 'KEYBOARD',
        rate: 5,
        wish: 0,
        imgList: [
            './images/products/product-19-img-1.jpg',
            './images/products/product-19-img-2.jpg',
            './images/products/product-19-img-3.jpg',
        ],
    },
    {
        id: 20,
        name: 'Razer BlackWidow V3 HALO Infinite Green',
        sale: 1941,
        price: 1490,
        category: 'KEYBOARD',
        rate: 4,
        wish: 0,
        imgList: [
            './images/products/product-20-img-1.jpg',
            './images/products/product-20-img-2.jpg',
            './images/products/product-20-img-3.jpg',
        ],
    },
    {
        id: 21,
        name: 'Leopold FC660MPD Blue Star',
        sale: 1941,
        price: 1490,
        category: 'KEYBOARD',
        rate: 4,
        wish: 0,
        imgList: [
            './images/products/product-21-img-1.jpg',
            './images/products/product-21-img-2.jpg',
            './images/products/product-21-img-3.jpg',
        ],
    },
    {
        id: 22,
        name: 'Apple Watch s6',
        sale: 1941,
        price: 1490,
        category: 'WATCH',
        rate: 5,
        wish: 0,
        imgList: [
            './images/products/product-22-img-1.jpg',
            './images/products/product-22-img-2.jpg',
            './images/products/product-22-img-3.jpg',
            './images/products/product-22-img-4.jpg',
        ],
        colorList: ['--pink:1', '--black:3', '--blue:4'],
    },
    {
        id: 23,
        name: 'Oppo Watch 41mm',
        sale: 1941,
        price: 1490,
        category: 'WATCH',
        rate: 5,
        wish: 0,
        imgList: [
            './images/products/product-23-img-1.jpg',
            './images/products/product-23-img-2.jpg',
            './images/products/product-23-img-3.jpg',
        ],
    },
    {
        id: 24,
        name: 'Galaxy Watch 4 Ite',
        sale: 1941,
        price: 1490,
        category: 'WATCH',
        rate: 5,
        wish: 0,
        imgList: [
            './images/products/product-24-img-1.jpg',
            './images/products/product-24-img-2.jpg',
            './images/products/product-24-img-3.jpg',
            './images/products/product-24-img-4.jpg',
        ],
    },
    {
        id: 25,
        name: 'Garmin Forerunner 45',
        sale: 1941,
        price: 1490,
        category: 'WATCH',
        rate: 4,
        wish: 0,
        imgList: [
            './images/products/product-25-img-1.jpg',
            './images/products/product-25-img-2.jpg',
            './images/products/product-25-img-3.jpg',
            './images/products/product-25-img-4.jpg',
            './images/products/product-25-img-5.jpg',
        ],
        colorList: ['--red:1', '--black:4', '--white:5'],
    },
    {
        id: 26,
        name: 'Corsair HS50 PRO',
        sale: 1941,
        price: 1490,
        category: 'HEADPHONE',
        rate: 5,
        wish: 0,
        imgList: [
            './images/products/product-26-img-1.jpg',
            './images/products/product-26-img-2.jpg',
            './images/products/product-26-img-3.jpg',
        ],
    },
    {
        id: 27,
        name: 'Asus ROG THETA 7.1',
        sale: 1941,
        price: 1490,
        category: 'HEADPHONE',
        rate: 5,
        wish: 0,
        imgList: [
            './images/products/product-27-img-1.jpg',
            './images/products/product-27-img-2.jpg',
            './images/products/product-27-img-3.jpg',
        ],
    },
    {
        id: 28,
        name: 'SteelSeries Arctis Pro 61486',
        sale: 1941,
        price: 1490,
        category: 'HEADPHONE',
        rate: 4,
        wish: 0,
        imgList: [
            './images/products/product-28-img-1.jpg',
            './images/products/product-28-img-2.jpg',
        ],
    },
    {
        id: 29,
        name: 'Kingston HyperX Cloud Alpha Gold - Limited Edition',
        sale: 1941,
        price: 1490,
        category: 'HEADPHONE',
        rate: 3,
        wish: 0,
        imgList: [
            './images/products/product-29-img-1.jpg',
            './images/products/product-29-img-2.jpg',
            './images/products/product-29-img-3.jpg',
        ],
    },
    {
        id: 30,
        name: 'ROG Zephyrus G14',
        sale: 1941,
        price: 1490,
        category: 'LAPTOP',
        rate: 5,
        wish: 0,
        imgList: [
            './images/products/product-15-img-1.jpg',
            './images/products/product-15-img-2.jpg',
            './images/products/product-15-img-3.jpg',
        ],
    },
];

let BILLS = [
    {
        id: 1,
        username: 'admin',
        products: [ 
            {
                id: 25,
                name: 'Garmin Forerunner 45',
                sale: 1400,
                price: 1941,
                category: 'WATCH',
                img: './images/products/product-25-img-1.jpg',
                quantity: 5,
                    
            }
        ],
        subtotal: 1239213,
        created_at: Date.now(),
        status: 'PENDING',
    },
    {
        id: 2,
        username: 'admin',
        products: [ 
            {
                id: 25,
                name: 'Garmin Forerunner 45',
                sale: 1941,
                price: 1490,
                category: 'WATCH',
                img: './images/products/product-25-img-1.jpg',
                quantity: 5,
                    
            }
        ],
        subtotal: 1239,
        created_at: Date.now(),
        status: 'COMPLETED',
    },
    {
        id: 3,
        username: 'user',
        products: [
            {
                id: 25,
                name: 'Garmin Forerunner 45',
                sale: 1941,
                price: 1490,
                category: 'WATCH',
                img: './images/products/product-25-img-1.jpg',
                quantity: 5,
                    
            }
        ],
        subtotal: 1239213,
        created_at: Date.now(),
        status: 'CANCELLED',
    },
];


